stages:
    - test
    - deploy
  
Test:
    stage: test
    image: python:3.7
    script:
        - apt-get update -qy
        - apt-get install -y python-dev python-pip
        - pip install -r requirements.txt
        - coverage run --source='.' manage.py test hello
        - coverage report
    only:
        - staging

Staging:
    stage: deploy
    image: ruby:2.7
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=masif --api-key=$HEROKU_STAGING_API_KEY
    only:
        - staging