stages:
  - test
  - deploy

services:
  - postgres:12-alpine
variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"

Test:
  stage: test
  image: python:3.7
  before_script:
    - apt-get update -qy
  script:
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - coverage run --source='.' manage.py test hello
    - coverage report
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'

SonarScanner:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
      -Dsonar.host.url=$SONARQUBE_HOST
      -Dsonar.login=$SONARQUBE_TOKEN
      -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME
