stages:
  - lint
  - test
  - sonarqube
  - deploy_staging

services:
  - postgres:12-alpine
variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"
  DOCKER_DRIVER: overlay2

Lint:
  stage: lint
  image: python:3.7
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - pylint --load-plugins=pylint_django --rcfile=.pylintrc  admin kesbangpol opd user -r n --exit-zero > pylint_report.txt
  artifacts:
    untracked: true
    expire_in: 1 hour
    paths:
      - pylint_report.txt

Test:
  stage: test
  image: python:3.7
  before_script:
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
    - apt-get update -qq && apt-get install -y -qq unzip
    - apt-get install -y google-chrome-stable
    - apt-get install -y xvfb
    - wget https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
    - unzip -o chromedriver_linux64.zip
    - mkdir /masif_uploaded_files
  script:
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
    - coverage run --source='.' manage.py test
    - coverage xml -i
    - coverage report
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  artifacts:
    untracked: true
    expire_in: 1 hour
    paths:
      - coverage.xml
      - pylint_report.txt

SonarScanner:
  stage: sonarqube
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
      -Dsonar.host.url=$SONARQUBE_HOST
      -Dsonar.login=$SONARQUBE_TOKEN
      -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME
      -Dsonar.python.coverage.reportPaths=coverage.xml
      -Dsonar.python.pylint.reportPath=pylint_report.txt
  dependencies:
    - Lint
    - Test

Staging:
  stage: deploy_staging
  image: ubuntu:latest
  before_script:
    - apt-get update -qq
    - apt-get install -qq git
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - mkdir -p .ssh
    - echo "$DEPLOYMENT_SSH" | tr -d '\r' > .ssh/ppl_masif.pem
    - chmod 700 .ssh/ppl_masif.pem
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - ssh-add .ssh/ppl_masif.pem
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh -tt $DEPLOYMENT_SERVER "
        cd abang-abang-masif/
        git checkout staging
        git pull origin staging
        docker-compose run web python manage.py makemigrations
        docker-compose run web python manage.py migrate
        docker-compose up -d
        docker rm $(docker ps -a -q -f status=exited)
        exit
        "
  only:
    - staging
