version: "3.7"

services:
  db:
    image: postgres:12-alpine
    restart: always
  web:
    build: .
    command: gunicorn masifapp.wsgi --bind 0.0.0.0:5000
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
