# Generated by Django 3.0 on 2020-03-17 00:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lowongan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=100)),
                ('kuota_peserta', models.IntegerField()),
                ('waktu_awal_magang', models.DateField()),
                ('waktu_akhir_magang', models.DateField()),
                ('batas_akhir_pendaftaran', models.DateField()),
                ('berkas_persyaratan', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('deskripsi', models.TextField(max_length=1000)),
                ('requirement', models.TextField(max_length=1000)),
                ('is_lowongan_masih_berlaku', models.BooleanField(default=True)),
                ('opd_foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowongan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
